FROM nvidia/cuda:13.1.0-base-ubi10 

LABEL maintainer='Michaël "e7d" Ferrand <michael@e7d.io>'
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin

RUN dnf makecache && \
    dnf -y install git golang && \
    dnf clean all

RUN go install github.com/mitranim/gow@latest && \
    mv $GOPATH/bin/gow /usr/bin/gow

WORKDIR /go

EXPOSE 9202

CMD [ "gow", "run", "app.go" ]
